### ISSUE TITLE
Implement a new feature to pick a window behind another window without the need to use alt+tab or taskbar

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#103]
There is an idea to be able to pick window that fully covered by other windows without using alt+tab or taskbar.
Implement this as a new feature that can be turn off/on

# Update:
After 23 days of works, here is the final result!

https://www.youtube.com/watch?v=eSM-CvmZ5jY

You can download from here: 
https://github.com/gileli121/WindowTop/releases/tag/v5.4.2

# Update v5.7.5:
![anchors_demo](https://user-images.githubusercontent.com/17680514/147421180-3f94be81-6f19-4a4d-8bb6-567ee016184f.gif)
![image](https://user-images.githubusercontent.com/17680514/147421176-9a4c4725-5a3c-4796-a29b-a746aacef2c5.png)

**Comment by gileli121** [comment]
Starting to implement it.
![windowtop-anchor-p1](https://user-images.githubusercontent.com/17680514/120151061-7f7cd300-c1f4-11eb-9e52-8ed542c34b84.gif)

The plan is that these "anchors" will be smart and will move to empty areas where there is no text/image on the screen.
For now this behavior is not implemented yet

**Comment by jakkaas** [comment]
Cool. It would be nice that it distinguish background app from active apps

**Comment by gileli121** [comment]
@jakkaas 
I consider that the idea is also that the opacity of each anchor will depends on how much the window is used.
For example, given that you have these windows:

* Window X
* Window Y

You use 90% of the time Window X
And you use 20% of the time Window Y

So the idea is that the opacity of the "anchor" of Window X will be 90% and the opacity of "anchor" of Window Y will be 20%
Is that make sense?

**Comment by jakkaas** [comment]
Yes. But allowing to manually include/exclude apps for which anchor could be applied would be great. It would be also a feasible idea to manually drag the anchor to whatever position I  like.

I am actually kind of use a function of software called actual window manager, where I could minimize any app/window on the screen. I use it a lot. It is kind of similar to what you want to achieve but I feel your implementation of it would be much better.

![image](https://user-images.githubusercontent.com/43289832/120361457-793b4380-c327-11eb-8602-2889047940f9.png)

On the right-hand side, I have kept OneNote minimized to screen.

**Comment by gileli121** [comment]
Yes, good option to be able to drag them.
My idea is that you will even will not need to move the anchors :)
It is crazy but I can make it smart... The anchors will not cover texts/images because they will move to blank area.
It can detect texts/images inside chrome or any window.

The things that the API in windows allows to do is crazy.
Just need to know very good how to use Windows APIs

**Comment by gileli121** [comment]
Now their positions are not collides with each other. This is the progress of today
![image](https://user-images.githubusercontent.com/17680514/120379033-d9ca8080-c327-11eb-96a0-df78f7cfecc5.png)

Next progress is to implement logic that their positions will moved to smart areas as I said (areas where there is no text/image behind)

**Comment by gileli121** [comment]
@jakkaas 
finally for the first time I managed to do it!
They moving to areas where there is no text or images automatically

This is a very very first result of the development but it should be good enough for working POC and for showing the idea :)

https://www.youtube.com/watch?v=1WZDvvaX64Y 

Let me know what you think

**Comment by jakkaas** [comment]
Great execution. The concept feels so refreshing and innovative. But I feel It might be slow or obstructive for a few. The manual option of rearranging and keeping at a certain position would be great. I believe auto arranging based on text/image position but only at any side of the screen (most of the free space is available at the side of screen) and not at center would also look good and innovative.

Also, how do you plan to color the anchor? In certain backgrounds, they might not be visible. 

Also do make it touch supportive. I would be using it on a touch screen which would be so much faster than alt-tab.

**Comment by gileli121** [comment]
Thanks for th feedback

> The manual option of rearranging and keeping at a certain position would be great

I will develop this option also

> believe auto arranging based on text/image position but only at any side of the screen (most of the free space is available at the side of screen) and not at center would also look good and innovative.

The idea that they not move to areas on the center of the screen is good. I did not thought about it. I will develop option that to auto rearranging algorithm will prefer non-center areas 

> Also, how do you plan to color the anchor? In certain backgrounds, they might not be visible.

They should be visible because the text have stroke around it


> Also do make it touch supportive. I would be using it on a touch screen which would be so much faster than alt-tab.

Yes, I did not thought about it that for touch this feature win for sure the alt+tab option.
I will make sure that it supports touch

**Comment by gileli121** [comment]
@jakkaas 
After more development, now it is working much faster and it also changes the opacity of each anchor by the z-order position of the window. If the z-order is 0, the opacity will be 100%. If it is 1, the opacity will be lower, and so on. 

See the new video:
https://www.youtube.com/watch?v=eYLhN9DVLFk

**Comment by gileli121** [comment]
@jakkaas 
> believe auto arranging based on text/image position **but only at any side of the screen** (most of the free space is available at the side of screen) and not at center would also look good and innovative.

Implemented another mode that the auto arranging will no longer keep try moving the anchors to the center of the screen.
See the new behavior in this video:
https://www.youtube.com/watch?v=MYUJ7J1IqEs

**Comment by gileli121** [comment]
New video after more progress. Now the settings UI is ready
https://www.youtube.com/watch?v=MYUJ7J1IqEs

**Comment by jakkaas** [comment]
Great. Would love to test the beta version. Its even unimaginable something like this could be done .

**Comment by gileli121** [comment]
I will upload beta version soon.
>  Its even unimaginable something like this could be done
This is why no one could request it :)

**Comment by gileli121** [comment]
@jakkaas 
Please test the following build:
[Build.zip](https://github.com/gileli121/WindowTop/files/6641917/Build.zip)

In the settings window, enable this option:
![image](https://user-images.githubusercontent.com/17680514/121771160-581ff180-cb76-11eb-815c-c675b8089700.png)

Let me know how it works

**Comment by gileli121** [comment]
@jakkaas 
Please try this build:
[Build.zip](https://github.com/gileli121/WindowTop/files/6642620/Build.zip)

Changes:
* settings window: added "Configure anchors for windows" in GettingStartedView
* settings window: added "Set default opacity level" link in GettingStartedView
* anchor feature: added inside ProVsFreeTableControl.xaml
* anchor feature: fixed issue that the window title of the anchors was a little wrong
* anchor feature: fixed (again) issue that program froze in case you disable the anchor feature
* anchor feature: fixed bug that the program froze in case you disable the anchor feature
* anchor feature: fixed bug that the anchors moving to the second screen and improved speed of mapping new screen elements
* anchor feature: fixed bug that the program can freze when picking window via anchor
* anchor feature: changed default settings

**Comment by gileli121** [comment]
@jakkaas 
Please also have a look on #108 and the video there
Let me know what you think

**Comment by jakkaas** [comment]
Hello I tried the build zip and ran the exe file as administrator but there was one window command prompt always open and the anchor was not working for me

![image](https://user-images.githubusercontent.com/43289832/121798251-dd70d800-cc42-11eb-8591-f16151598685.png)

https://drive.google.com/file/d/1fVKXvEduzV0qkD39Qu-a9YBkv4OfwU9X/view?usp=sharing

Few observations.

1) The switching of window using anchor was fast.

2) The anchors size were large for my small size screen. You should also provide the option of adjusting anchor size.

3) While using alt-tab (not required using anchor but sometimes one may use both)/win-tab, the anchors are also seen as an individual window. If possible the anchors should be running in the background instead of individual windows.

4) if one has disabled z mode for switching anchor (auto mode) then one should be able to drag the anchor (maybe using double click and drag ) & or given the option of where to keep the anchors. I don't know if such a function was available and not working for me.

5) you could also integrate your new app window bar using anchor. if one uses windowbar along with windowtop than anchor can enhance the functions of the windowbar.

**Comment by gileli121** [comment]
@jakkaas 

> The switching of window using anchor was fast.
Great!

> The anchors size were large for my small size screen. You should also provide the option of adjusting anchor size.
OK, I will add this option also

> While using alt-tab (not required using anchor but sometimes one may use both)/win-tab, the anchors are also seen as an individual window. If possible the anchors should be running in the background instead of individual windows.
Do you mean to this?
![image](https://user-images.githubusercontent.com/17680514/121805212-dfdb2e00-cc52-11eb-81fe-7f5e819a5a10.png)
I will fix it. Thanks for the report

> if one has disabled z mode for switching anchor (auto mode) then one should be able to drag the anchor (maybe using double click and drag ) & or given the option of where to keep the anchors. I don't know if such a function was available and not working for me.
There was no such function to manually drag them


> you could also integrate your new app window bar using anchor. if one uses windowbar along with windowtop than anchor can enhance the functions of the windowbar.
WindowBar project is deprecated due to reasons here:
https://github.com/gileli121/WindowBar/issues/3
If you don't agree with the reasons let me know. I don't belive that this project will have success like WindowTop

**Comment by jakkaas** [comment]
Please also give an option of manually adjusting the anchor.

And yes I also thought no use of window bar for myself yet. But along with integration with anchor and function similar to kind of groupy it could be quite useful.

**Comment by gileli121** [comment]
@jakkaas 

> While using alt-tab (not required using anchor but sometimes one may use both)/win-tab, the anchors are also seen as an individual window. If possible the anchors should be running in the background instead of individual windows.

Fixed

> if one has disabled z mode for switching anchor (auto mode) then one should be able to drag the anchor (maybe using double click and drag ) & or given the option of where to keep the anchors. I don't know if such a function was available and not working for me.

I added now option to manually drag them by holding the mouse left button and drag it.

Try this build:
[Build 14.6.21.zip](https://github.com/gileli121/WindowTop/files/6645988/Build.14.6.21.zip)

**Comment by jakkaas** [comment]
manual switching is working but there is an issue that when I click on anchor and window changes, it also switches the position of that anchor.

**Comment by jakkaas** [comment]
But I don't know auto switching is still not working for me. I don't know weather old install or any other program is causing this issue.

**Comment by gileli121** [comment]
@jakkaas 
This bug
![image](https://user-images.githubusercontent.com/17680514/121997088-6b1f0580-cdb2-11eb-9d25-552a9680d1b6.png)

Must be fixed. To be sure that you using the last version, please download this build:
[Build 15.6.21.zip](https://github.com/gileli121/WindowTop/files/6653085/Build.15.6.21.zip)


Extract it and run it from the extracted folder. Don't copy the WindowTop.exe file to anywhere else. Run it inside the extracted folder. The reason is because in the extracted folder you have the file WindowTopLog.log

Reproduce this issue that the anchors 
[Build 15.6.21.zip](https://github.com/gileli121/WindowTop/files/6653080/Build.15.6.21.zip)
not moving. After that, you should get this file:
![image](https://user-images.githubusercontent.com/17680514/121998516-a1f61b00-cdb4-11eb-9773-9b750f8fd06c.png)

The content of the file should be something like this:
![image](https://user-images.githubusercontent.com/17680514/121998595-c05c1680-cdb4-11eb-8630-4b91d61d3f78.png)

In addition, you will also see 2 black command line windows. This is because it is debug version... Don't close them because it can close the program.

In addition, please also go to this page
![image](https://user-images.githubusercontent.com/17680514/121998745-05804880-cdb5-11eb-9751-5a647fb94707.png)
And verify that you see v5.4.0

**Comment by gileli121** [comment]
@jakkaas 
After that, please send me the "WindowTopLog.log" file

**Comment by gileli121** [comment]
@jakkaas 
I saw the log. This is the issue there:
```log
WindowTop.Logic.ScreenElementsManager(DEBUG): Screen elements count: 0
```

It did not detected elements on the screen (texts/images) so it will never move the anchors/shrink-boxes to another position because it always assumes that it covers nothing.


I will try to figure it out

**Comment by jakkaas** [comment]
Is it because of two screen overlay software i use for reducing eye strain
1) colorveil2) eyecare
Sent from Yahoo Mail on Android 
 
  On Tue, Jun 15, 2021 at 9:26 PM, Gil ***@***.***> wrote:   


@jakkaas
I saw the log. This is the issue there:
WindowTop.Logic.ScreenElementsManager(DEBUG): Screen elements count: 0

It did not detected elements on the screen (texts/images) so it will never move the anchors/shrink-boxes to another position because it always assumes that it covers nothing.

I will try to figure it out

**Comment by gileli121** [comment]
@jakkaas 
You are right!
The idea that the issue caused by colorveil makes very sense according to the logs.
I checked it now and I was able to reproduce the issue when the program colorveil runned and did its stuff.

I know what is wrong in the logic and how to fix it. I will fix the bug now

**Comment by gileli121** [comment]
@jakkaas 
I fixed the issue.
Please test it with this build:
[Build 15.6.21-2.zip](https://github.com/gileli121/WindowTop/files/6658297/Build.15.6.21-2.zip)
Let me know if it fixed for you


Note that in this build I also started to implement option to configure the size, font of the anchors but for now it is not working yet in this build.
This is how it starts to look:
![image](https://user-images.githubusercontent.com/17680514/122114595-20da6a80-ce2c-11eb-880e-e1766e69ee28.png)

**Comment by jakkaas** [comment]
Great. It's working now. Please also add an option of not moving anchor automatically and kept at a fixed position.

**Comment by gileli121** [comment]
@jakkaas 
> 2. The anchors size were large for my small size screen. You should also provide the option of adjusting anchor size.

Implemented. Please download this build:
[Build 16.6.21-1.zip](https://github.com/gileli121/WindowTop/files/6660429/Build.16.6.21-1.zip)

I also changed the icon to simple ellipse. This looks better and the icon could be smaller this way

**Comment by jakkaas** [comment]
> @jakkaas
> 
> > 1. The anchors size were large for my small size screen. You should also provide the option of adjusting anchor size.
> 
> Implemented. Please download this build:
> [Build 16.6.21-1.zip](https://github.com/gileli121/WindowTop/files/6660429/Build.16.6.21-1.zip)
> 
> I also changed the icon to simple ellipse. This looks better and the icon could be smaller this way

The build is working perfectly. I can easily modify the size as per my need.

**Comment by gileli121** [comment]
@jakkaas 
> Please also add an option of not moving anchor automatically and kept at a fixed position.

Implemented. Please download this build:
[Build 18.6.21-1.zip](https://github.com/gileli121/WindowTop/files/6673282/Build.18.6.21-1.zip)


Full changing logs from GIT:

* anchor feature: implemented logic to avoid reloading the DOM in case of user inputs. (This will reduce CPU usage and cases that the window froze for a second when auto-move enabled)
* anchor feature: auto-mode: reduced amount of processing cycels to reduce CPU usage
* anchor feature: fixed issue that sometimes the window becomes topmost after picking it (maybe it is still not fixed)
* anchor feature: implemented option to configure auto move via settings window
* added logic to abort ScreenElementsManager threads if they running in case of exiting the program (this will speed up the exit-program option)
* anchor feature: anchor icon changed to ellipse
* anchor feature: implemented option to configure the anchor size via settings window
* shrink feature: fixed regression that shrink windows not recovered and even if they recovered, they recovered with invalid opacity
* settings: toolbar: fixed regression that the program crash when the mouse is above the shrink button in the settings window

**Comment by jakkaas** [comment]
Please have a look at this video
https://drive.google.com/file/d/1HoYPF6UdzzKoutxq1awt2_Vrj88_ceFR/view?usp=sharing

On turning off Automatically move anchor, Once the anchor is clicked, it disappears even after switching to other windows. I.e the Anchors are disappearing after it's clicked.

On the above note, I would like the anchor of that window to stay on screen even it is clicked. I.e  Currently when an anchor is clicked, the window comes on top of the screen and its anchor disappear (makes sense, since the window is at the top). But what I would like that (my greed :) ) that even when I click the anchor, it should be visible even if the window is on top (currently on screen) and if I click the anchor of this window once more than its get minimized.

It would be more interesting (maybe in further builds) to give an option of disabling anchor for background apps (windows UWP apps running in the background are picked up by anchor) & also allowing the minimized window to be picked up by anchor (I think so minimised windows are not picked up by anchor.)

Another thing that I observed in the previous build but can't test right now because of above issue is that once the position is fixed the anchor should not be changing position on clicking and then once the window is switched to another app, the anchor position gets changed.

Thanks

**Comment by gileli121** [comment]
@jakkaas 
What I am seeing in the video is a bug or a behavior that you want to improve?

> On the above note, I would like the anchor of that window to stay on screen even it is clicked. I.e Currently when an anchor is clicked, the window comes on top of the screen and its anchor disappear (makes sense, since the window is at the top). But what I would like that (my greed :) ) that even when I click the anchor, it should be visible even if the window is on top (currently on screen) and if I click the anchor of this window once more than its get minimized.

> also allowing the minimized window to be picked up by anchor (I think so minimised windows are not picked up by anchor.)

I don't think that they should show also when the window is minimized or not covered.
The whole idea of this feature is to deal with the _**covered window problem**_ 
People try to deal with the problem using the alt+tab option. but alt+tab is slower than this method.
They also try to deal with the problem using the set-top feature.. this is why it is the most used feature.
I believe that the anchors feature is the best method to handle the _**covered window problem**_

But once you suggested that they will show not only for covered window but also for minimized windows and anything else, then you change the original problem that the feature tries to solve - You no longer deal with covered windows only.. but now you deal with minimized... 


At this point, we are starting to replace the taskbar and alt+tab.
And if you replace something, it comes with a price... harder problems mean a higher price.


taskbar: used for minimized windows
alt+tab: used for all windows. it is a fast replace method but it is not super fast because you need more keyboard clicks (minimum 2) and because it shows all windows
anchors: used to be able to access very very fast in one click the top 5 windows  (depends on the default settings. 5 is the default) that you use the most (and they not minimized, just covered)

What if you want that in some cases the anchor will not be shown (this is a something you may want especially if the anchors amount is unlimited)? in the current implementation, you only need to minimize the window. But in the suggested implementation, it will not help.. So the fact that I don't show it for minimizing window is an advantage,

You also always can go to the window with alt+tab in case it is minimized.

The idea is also to show you always anchor only for the most used windows. minimized windows are less used than covered windows


> It would be more interesting (maybe in further builds) to give an option of disabling anchor for background apps (windows UWP apps running in the background are picked up by anchor)

This is a bug.. I saw it before.. I will work on fix


> Another thing that I observed in the previous build but can't test right now because of above issue is that once the position is fixed the anchor should not be changing position on clicking and then once the window is switched to another app, the anchor position gets changed.

Thanks for the report. I will check it

**Comment by jakkaas** [comment]
Thanks. I understand.

"On turning off Automatically move anchor, Once the anchor is clicked, it disappears even after switching to other windows. I.e the Anchors are disappearing after it's clicked."

This the bug. As you can see in the video, Once I click anchor, that window appears. Then I click another anchor and its window appear. But the 1st window anchor should now be seen which is not the case. Slowly on clicking other anchors, previous window anchors are disappearing.

**Comment by gileli121** [comment]
@jakkaas 
When the anchor disappears, it reappears again when the window is fully covered (not minimized, only covered)?

**Comment by gileli121** [comment]
@jakkaas 
In the video I see for sure that in some case, the anchor going back to the old position. I think that it is because auto-move disabled.

Please check this build:
[Build 18.6.21-2.zip](https://github.com/gileli121/WindowTop/files/6675104/Build.18.6.21-2.zip)

I hope that the issue fixed

**Comment by jakkaas** [comment]
Same issue as above.
Suppose there are 4 windows a,b,c & d, all maximised & its anchors

In auto mode, if I click anchor a, a window appear and I can see 3 anchors b, c & d.
If I click b anchor, window b appear and I can see 3 anchors a,c & d.

If I diable auto mode. After that if I click anchor a, a window appear and I can see 3 anchors b, c & d.
Now if I click b anchor, window b appear and I can only see 2 anchors c & d.
I click c anchor, window c appear and I can see 1 anchors d.

(This is seen in the video shared above after disabling auto mode)

**Comment by gileli121** [comment]
@jakkaas 
I understand the bug now. I also see it in the video

**Comment by gileli121** [comment]
@jakkaas 
Please download and run this build:
[Build 18.6.21-3-debug.zip](https://github.com/gileli121/WindowTop/files/6675898/Build.18.6.21-3-debug.zip)

Run WindowTop.exe directly inside "Build 18.6.21-3-debug" folder.
The important part is the file NLog.config there. With this file, the program will create "WindowTopLog.log" file.

Please reproduce the issue. 
Once the issue reproduced, exit WindowTop and send me the "WindowTopLog.log" file

The log should look like this:
![image](https://user-images.githubusercontent.com/17680514/122535544-58b00080-d02c-11eb-8c8e-78af2a26ad86.png)

**Comment by gileli121** [comment]
@jakkaas 
I got the logs.
According to the logs, the the program processed all the time 5 anchors.
But you say that at some point some of them was not shown so you saw less than 5?
Is that correct?

**Comment by jakkaas** [comment]
Yes, Initially it's showing 5.

<img width="960" alt="1_1" src="https://user-images.githubusercontent.com/43289832/122554632-dee13c80-d056-11eb-9e44-39c899771df2.png">


<img width="960" alt="1_3" src="https://user-images.githubusercontent.com/43289832/122555030-5f07a200-d057-11eb-8da7-4512edbcab10.png">


but randomly just by Alt-Tab/Win-Tab or by clicking anchors, it only shows 1. It keeps on changing and it even becomes no anchor.

<img width="960" alt="1_2" src="https://user-images.githubusercontent.com/43289832/122555319-c6255680-d057-11eb-9b5f-20679e045174.png">


![image](https://user-images.githubusercontent.com/43289832/122554963-44352d80-d057-11eb-98bc-b5a65fa69b7d.png)

**Comment by gileli121** [comment]
@jakkaas 
Can you try to reproduce the issue with only one virtual desktop?

**Comment by gileli121** [comment]
@jakkaas 
What is the program that doing this:
![image](https://user-images.githubusercontent.com/17680514/122580154-549cd680-d05e-11eb-9928-94871000d8ef.png)

I know that you using stardock groupy but what is the second program you use?
It may causing the issue

**Comment by gileli121** [comment]
I can't reproduce this issue. Maybe some of the programs you are using are conflicting with WindowTop as it was before

**Comment by gileli121** [comment]
@jakkaas 
I suspect that it has something to do with the virtual desktop built-in feature in Windows 10.
I think that there is some scenario that reproduces it but I can't figure it out.

Anyway, there is a bug with multiple virtual desktops. The bug is that it shows anchors from another virtual desktop.
In theory, it can also think that a window is covered by another window even if it is actually not covered at all.. and this is because the other window is not on the same virtual desktop. This theory explains the logs and also the bug you saw. 
But I could not prove it.

Still, I added logic to handle multiple virtual desktops so now the program will no think that a window is covered by another window from a different virtual desktop.

In addition, there was also a bug in the set-top -> highlight mode.. that the red highlighter was showing in any virtual desktop and not on the virtual desktop where the window belongs to. 
This is a bug I found while trying to figure out this bug.

Please try this build and let me know if it fixed:
[Build 18.6.21-4.zip](https://github.com/gileli121/WindowTop/files/6678450/Build.18.6.21-4.zip)

**Comment by jakkaas** [comment]
@gileli121 

Please watch this recording.

https://drive.google.com/file/d/1flkiSFX92tVWi3n_2QzkRjZasmgLkOO8/view?usp=sharing

I have closed all virtual desktop, background apps and few services too. But same issue.

in Auto mode Anchor are not disappearing, while in manual mode the anchor disappears. Sometime blinking of  an anchor is seen between and its gone.

**Comment by gileli121** [comment]
@jakkaas 
Good news!
I cracked it.. The issue reproduced on my side.
The secret is to set DPI to more than 100%
![image](https://user-images.githubusercontent.com/17680514/122638802-e8be7a80-d0fe-11eb-9d9e-6a35ded812cf.png)

And to disable auto-move mode.
This is the secret.

Now I will work on fix.
Thanks for the bug report

**Comment by gileli121** [comment]
@jakkaas 
Fixed.. 
![image](https://user-images.githubusercontent.com/17680514/122639166-ed842e00-d100-11eb-9481-262785d96d90.png)

Please check this build:
[Build 19.6.21-1.zip](https://github.com/gileli121/WindowTop/files/6680485/Build.19.6.21-1.zip)

Let me know if it fixed

**Comment by gileli121** [comment]
In addition, I also fixed some bug in the auto-move mode that sometimes the anchors moving without a valid reason.
I think that you mentioned it already

Full change logs from GIT:

* anchor feature: fixed issue that after picking window from anchor, sometimes the mouse always stays as pointer
* anchor feature: fixed bug that the anchors reset their position in auto-move mode after they show again
* fixed small issues in AutoMovableWinsManager
* anchor feature: fixed bug that elements moving after picking window from anchor because it did not update the DOM after picking window
* anchor feature: fixed issue that when DPI is more than 100% and auto-move disabled, the anchors are "not visible"

**Comment by jakkaas** [comment]
Great. Finally. All your effort has been paid off. It is finally working as expected.

**Comment by gileli121** [comment]
@jakkaas 

Great!
Implemented option to enable/disable anchors from tray menu
![image](https://user-images.githubusercontent.com/17680514/122644347-714c1380-d11d-11eb-8542-db8a2b47a80a.png)

Last build:
[Build 19.6.21-2.zip](https://github.com/gileli121/WindowTop/files/6680788/Build.19.6.21-2.zip)


> It would be more interesting (maybe in further builds) to give an option of disabling anchor for background apps (windows UWP apps running in the background are picked up by anchor) & also allowing the minimized window to be picked up by anchor (I think so minimised windows are not picked up by anchor.)

Do you still get this issue? Maybe it fixed as part of the fix for the multiple virtual desktops


> Also, it would be a good enhancement if the anchor could also show a small icon size of the window it is showing along with the text.

This is something that maybe I will implement but not in the first final release

**Comment by gileli121** [comment]
@jakkaas 

For now, this should be the final build where the feature is fully developed and tested.
The only missing stuff is the translation to Chinese and german.


[Build 19.6.21-3.zip](https://github.com/gileli121/WindowTop/files/6681007/Build.19.6.21-3.zip)

In this build, I improved the auto-move mode...
Now it will able to detect more areas with texts. Before the update, it could miss more areas with texts.
Now it should miss less. As a result, it will be smarter when it moves the anchors/shrink items.

**Comment by jakkaas** [comment]
Yes background apps are not seen after Build 19.6.21-1.zip

**Comment by gileli121** [comment]
Great!
Here is a final release
https://github.com/gileli121/WindowTop/releases/tag/v5.4.x
For now it still marked as pre-release but I will mark it as final soon after we will be sure that it is good version.

This version includes #103 and #108 and also all missing translations

**Comment by jakkaas** [comment]
Working as Intended except for background apps of Windows UWP seen If Anchors are set more than number of active windows available currently.

**Comment by gileli121** [comment]
@jakkaas 
Please try this build:
[Build 21.6.21-1.zip](https://github.com/gileli121/WindowTop/files/6684357/Build.21.6.21-1.zip)

The problem that it show anchors for background UWP apps should be fixed in this build

**Comment by gileli121** [comment]
I already tested it on computer that it always reproduced.
I released this build as version v5.4.3

**Comment by gileli121** [comment]
@jakkaas 
Here is more recent version of this feature:
![image](https://user-images.githubusercontent.com/17680514/147421176-9a4c4725-5a3c-4796-a29b-a746aacef2c5.png)
![anchors_demo](https://user-images.githubusercontent.com/17680514/147421180-3f94be81-6f19-4a4d-8bb6-567ee016184f.gif)

Let me know what you think.
It is available in v5.7.5

**Comment by jakkaas** [comment]
Very stable, nice and quick. Great. But as per released note, icon are not seen yet in Anchor.

**Comment by gileli121** [comment]
@jakkaas 
Great!
I have another idea now.

What if I add an option (you can disable/enable it) that when the anchor is visible, it will hide the button in the taskbar?
After all, if you use the window anchor, you are not likely to access it from the taskbar.
So the feature will remove the button in the taskbar when the anchor is visible.
This way you have a more clean taskbar.

For example, the buttons in red will be removed because you can access them via the anchors:
![image](https://user-images.githubusercontent.com/17680514/147612381-c534d86c-1f0e-4acc-885f-4483615097f5.png)

When the anchor is removed, it will make the button in the taskbar visible again.

**Comment by jakkaas** [comment]
Taskbar would not be needed as such if Anchors are used. It would be even more great if you could replicate windows taskbar feature on Anchors such as 
1) drag and drop in Anchor (Not available in Windows 11), 
2) Same app windows count, 
3) taskbar badges (If possible, you could even replicate android unread notification badges in numbers)
4) Combine anchor for Windows from same app and split it while moving cursor on it, etc.

Looking forward for yours innovative idea and its application.

If possible, you also give option of hiding text for anchors if icon are selected.

**Comment by gileli121** [comment]
Good ideas!
Thanks!

I think that I will start with: 
* Option of hiding text for anchors if icon are selected.


I just hope that the losers from Microsoft will not copy this idea also (they start now to copy the idea to set window on top for they stupid PowerToys product)

**Comment by gileli121** [comment]
@jakkaas 
So you agree to have option to hid the taskbar button when the window anchor available?
The option will be disabled by default

**Comment by gileli121** [comment]
I will work first on:
Implement drag/drop to window via the anchor (#180)

**Comment by gileli121** [comment]
@jakkaas 

Here it is:

![drag_to_anchor_demo](https://user-images.githubusercontent.com/17680514/147712105-7ac2ffb5-410a-4c8f-9649-2fb2f5b2b2b1.gif)

You can try the build from here:
https://github.com/BiGilSoft/WindowTop/issues/180

**Comment by gileli121** [comment]
@jakkaas 
See this one:
![anchor_hide_text_demo](https://user-images.githubusercontent.com/17680514/147790290-83d273f7-ad8c-4962-a4e5-f632458a483f.gif)

Looks good?
