### ISSUE TITLE
Issue with dark-mode and glass-mode on dual monitor configuration when DPI scaling is not the same for each monitor

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#9]
A user was reported that the Application is failing when you have 2 monitors, each one set with different DPI scaling. 

In such a case, the dark-mode renderer will fail to work correctly.

User setup:

- Dual screen, one screen is set to 150%
- second screen is set to 200% scale.

> Application is failing in 200%, in 150% scale it switches to dark mode, but some menus (File-> ... ) are still white.

**Comment by gileli121** [comment]
Part of the issue was that the toolbar menu was not placed at the top of the window on second monitor that have different DPI scaling.

This fix is released in v3.4.6

The second part of the issue is with dark mode and the aero. 
The second part not fixed yet.

**Comment by sd309991** [comment]
Hello, Gileli, has this issue been fixed? I have a second screen and the dark mode make my foxit reader very small and not in the centre of the window.

**Comment by gileli121** [comment]
@sd309991 
It fixed in [WindowTop 5.19.0-beta4](https://github.com/BiGilSoft/WindowTop/files/9768540/WindowTop.5.19.0-beta4.-.setup.exe.zip)

More information here:
https://github.com/BiGilSoft/WindowTop/issues/264#issuecomment-1276716577

Let me know how it works for you.

**Comment by gileli121** [comment]
@sd309991 
Please skip beta4 and try beta5 from here https://github.com/BiGilSoft/WindowTop/issues/264#issuecomment-1276763411
Thank you.

**Comment by DavidHJong** [comment]
> @sd309991 Please skip beta4 and try beta5 from here [#264 (comment)](https://github.com/BiGilSoft/WindowTop/issues/264#issuecomment-1276763411) Thank you.

I tested 5.19.1.0 on windows 10 x64 and there's still a problem. when I move the task manager to my second monitor, the dark image doesn't fully cover the window. I'm using two 2k monitor with 150% scaling factor.

**Comment by gileli121** [comment]
@DavidHJong 
The fix may not work on Windows 10.
I reproduced and fixed it in Windows 11.
Do you plan to upgrade to Windows 11? Microsoft provides a free upgrade to Windows 11, so if you don't care to upgrade to Windows 11, this may be the workaround for your issue. After you upgrade to Windows 11, there is a built-in option to go back to Windows 10 in case you don't want it, or it did not fix the issue.

Unfortunately, I plan to invest less development effort into this because it is too challenging, and I worked on it for almost two months (in improving the stability and performance). However, it is good enough if it works well on Windows 11. This was not the case before 5.19, for sure.

**Comment by DavidHJong** [comment]
@gileli121 Thank you for your reply, but I'm now ready to upgrade to windows 11 yet. btw, do you think the DPI scaling feature is more well-designed in windows 11 than in windows 10?

**Comment by DavidHJong** [comment]
@gileli121 Also, it seems that vast majority is still using windows 10 and this trend has not changed dramatically. ([(https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide)])
So, I think fixing this for windows 10 is still relevant.

**Comment by DavidHJong** [comment]
@gileli121 if you find fixing this bug for windows 10 demanding, I have an alternative remedy, disabling dark mode when the window is on 2nd monitor. This way the mismatched dark image over the window is not that bothering [like this. ](https://imgur.com/gallery/PeNjmjl)

**Comment by gileli121** [comment]
@DavidHJong 
OK, I will try to fix it for Windows 10 when I get to it.

**Comment by DavidHJong** [comment]
That's appreciated. 
btw, I find paid functionalities great and hope more people will see their value and support you.

**Comment by gileli121** [comment]
@DavidHJong 
Thanks for the feedback and for supporting the business :)

This was already fixed and released some time ago, and this ticket seems to be a duplicate.
Closed.
